import java.util.Date;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    

    public static void main(String[] args) {
       
    	SessionFactory factory = new Configuration().configure("hibernate.cfg.xml").buildSessionFactory();
    	
    	Student st = new Student();
    	 st.setName("Parvej");
    	 st.setDepartment("Computer Science and Science");
    	 st.setCourse("B.Tech");
    	 st.setRegistration(new Date());
    	 st.setIgn(122.453);
    	
    		Student st1 = new Student();
       	 st1.setName("Yogender");
       	 st1.setDepartment("Civil_department");
       	 st1.setCourse("B.Tech");
       	 st1.setRegistration(new Date());
       	 st1.setIgn(123.452);
    	 
    	 // creating session
    	 
    	Session s = factory.openSession();
    	Transaction tx = s.beginTransaction();
    	
    	// save
    	
    	/*s.save(st);
    	s.save(st1);*/
    	
    	// fetch -- using Get method
    	
    /*	Student std =(Student)s.get(Student.class, 3);
    	System.out.println(std);
    	
    	//System.out.println(std.getName() + ":" + std.getDepartment() + ":" + std.getRegistration());
    	
    	Student std1 =(Student)s.get(Student.class, 2);
    	System.out.println(std1.getName() + ":" + std1.getDepartment() + ":" + std1.getRegistration());*/
    	
    	//   fetch -- using load method
    	
    	Student std1 = (Student)s.load(Student.class, 1);
    	System.out.println(std1.getName() + " : " + std1.getDepartment() + " : " + std1.getRegistration());
    	
    	Student std2 = (Student)s.load(Student.class, 1);
    	
    	tx.commit();
    	s.close();
    	factory.close();
    }
}
